language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - python install.py
  - pip install coveralls

script:
  - export PYTHONWARNINGS=all
  - python setup.py test
  - coverage run --source="./client" --omit="*__init__.py,*__main__.py" setup.py test

after_success:
  coveralls
